package model.entidad;
// Generated Jan 28, 2016 8:13:11 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CgStore generated by hbm2java
 */
public class CgStore  implements java.io.Serializable {


     private Integer storeId;
     private String storeName;
     private String storeAddress;
     private String storeCity;
     private String storeCoordinateLatitude;
     private String storeCoordinateLongitude;
     private String storeState;
     private String storePhone;
     private String storeZip;
     private String storeLogo;
     private String storeVisible;
     private int storeAreaId;
     private String storeContactName;
     private String storeEmail;
     private String storeWeb;
     private String storeFacebook;
     private String storeComments;
     private Date storeDate;
     private String storeFeatured;
     private int storeCategoryId;
     private String storeImage1;
     private String storeImage2;
     private String storeImage3;
     private String storeImage4;
     private String storeImage5;

    public CgStore() {
    }

	
    public CgStore(String storeName, String storeAddress, String storeCity, String storeCoordinateLatitude, String storeCoordinateLongitude, String storeState, String storeZip, String storeLogo, String storeVisible, int storeAreaId, String storeContactName, String storeComments, Date storeDate, String storeFeatured, int storeCategoryId) {
        this.storeName = storeName;
        this.storeAddress = storeAddress;
        this.storeCity = storeCity;
        this.storeCoordinateLatitude = storeCoordinateLatitude;
        this.storeCoordinateLongitude = storeCoordinateLongitude;
        this.storeState = storeState;
        this.storeZip = storeZip;
        this.storeLogo = storeLogo;
        this.storeVisible = storeVisible;
        this.storeAreaId = storeAreaId;
        this.storeContactName = storeContactName;
        this.storeComments = storeComments;
        this.storeDate = storeDate;
        this.storeFeatured = storeFeatured;
        this.storeCategoryId = storeCategoryId;
    }
    public CgStore(String storeName, String storeAddress, String storeCity, String storeCoordinateLatitude, String storeCoordinateLongitude, String storeState, String storePhone, String storeZip, String storeLogo, String storeVisible, int storeAreaId, String storeContactName, String storeEmail, String storeWeb, String storeFacebook, String storeComments, Date storeDate, String storeFeatured, int storeCategoryId, String storeImage1, String storeImage2, String storeImage3, String storeImage4, String storeImage5) {
       this.storeName = storeName;
       this.storeAddress = storeAddress;
       this.storeCity = storeCity;
       this.storeCoordinateLatitude = storeCoordinateLatitude;
       this.storeCoordinateLongitude = storeCoordinateLongitude;
       this.storeState = storeState;
       this.storePhone = storePhone;
       this.storeZip = storeZip;
       this.storeLogo = storeLogo;
       this.storeVisible = storeVisible;
       this.storeAreaId = storeAreaId;
       this.storeContactName = storeContactName;
       this.storeEmail = storeEmail;
       this.storeWeb = storeWeb;
       this.storeFacebook = storeFacebook;
       this.storeComments = storeComments;
       this.storeDate = storeDate;
       this.storeFeatured = storeFeatured;
       this.storeCategoryId = storeCategoryId;
       this.storeImage1 = storeImage1;
       this.storeImage2 = storeImage2;
       this.storeImage3 = storeImage3;
       this.storeImage4 = storeImage4;
       this.storeImage5 = storeImage5;
    }
   
    public Integer getStoreId() {
        return this.storeId;
    }
    
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }
    public String getStoreName() {
        return this.storeName;
    }
    
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }
    public String getStoreAddress() {
        return this.storeAddress;
    }
    
    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress;
    }
    public String getStoreCity() {
        return this.storeCity;
    }
    
    public void setStoreCity(String storeCity) {
        this.storeCity = storeCity;
    }
    public String getStoreCoordinateLatitude() {
        return this.storeCoordinateLatitude;
    }
    
    public void setStoreCoordinateLatitude(String storeCoordinateLatitude) {
        this.storeCoordinateLatitude = storeCoordinateLatitude;
    }
    public String getStoreCoordinateLongitude() {
        return this.storeCoordinateLongitude;
    }
    
    public void setStoreCoordinateLongitude(String storeCoordinateLongitude) {
        this.storeCoordinateLongitude = storeCoordinateLongitude;
    }
    public String getStoreState() {
        return this.storeState;
    }
    
    public void setStoreState(String storeState) {
        this.storeState = storeState;
    }
    public String getStorePhone() {
        return this.storePhone;
    }
    
    public void setStorePhone(String storePhone) {
        this.storePhone = storePhone;
    }
    public String getStoreZip() {
        return this.storeZip;
    }
    
    public void setStoreZip(String storeZip) {
        this.storeZip = storeZip;
    }
    public String getStoreLogo() {
        return this.storeLogo;
    }
    
    public void setStoreLogo(String storeLogo) {
        this.storeLogo = storeLogo;
    }
    public String getStoreVisible() {
        return this.storeVisible;
    }
    
    public void setStoreVisible(String storeVisible) {
        this.storeVisible = storeVisible;
    }
    public int getStoreAreaId() {
        return this.storeAreaId;
    }
    
    public void setStoreAreaId(int storeAreaId) {
        this.storeAreaId = storeAreaId;
    }
    public String getStoreContactName() {
        return this.storeContactName;
    }
    
    public void setStoreContactName(String storeContactName) {
        this.storeContactName = storeContactName;
    }
    public String getStoreEmail() {
        return this.storeEmail;
    }
    
    public void setStoreEmail(String storeEmail) {
        this.storeEmail = storeEmail;
    }
    public String getStoreWeb() {
        return this.storeWeb;
    }
    
    public void setStoreWeb(String storeWeb) {
        this.storeWeb = storeWeb;
    }
    public String getStoreFacebook() {
        return this.storeFacebook;
    }
    
    public void setStoreFacebook(String storeFacebook) {
        this.storeFacebook = storeFacebook;
    }
    public String getStoreComments() {
        return this.storeComments;
    }
    
    public void setStoreComments(String storeComments) {
        this.storeComments = storeComments;
    }
    public Date getStoreDate() {
        return this.storeDate;
    }
    
    public void setStoreDate(Date storeDate) {
        this.storeDate = storeDate;
    }
    public String getStoreFeatured() {
        return this.storeFeatured;
    }
    
    public void setStoreFeatured(String storeFeatured) {
        this.storeFeatured = storeFeatured;
    }
    public int getStoreCategoryId() {
        return this.storeCategoryId;
    }
    
    public void setStoreCategoryId(int storeCategoryId) {
        this.storeCategoryId = storeCategoryId;
    }
    public String getStoreImage1() {
        return this.storeImage1;
    }
    
    public void setStoreImage1(String storeImage1) {
        this.storeImage1 = storeImage1;
    }
    public String getStoreImage2() {
        return this.storeImage2;
    }
    
    public void setStoreImage2(String storeImage2) {
        this.storeImage2 = storeImage2;
    }
    public String getStoreImage3() {
        return this.storeImage3;
    }
    
    public void setStoreImage3(String storeImage3) {
        this.storeImage3 = storeImage3;
    }
    public String getStoreImage4() {
        return this.storeImage4;
    }
    
    public void setStoreImage4(String storeImage4) {
        this.storeImage4 = storeImage4;
    }
    public String getStoreImage5() {
        return this.storeImage5;
    }
    
    public void setStoreImage5(String storeImage5) {
        this.storeImage5 = storeImage5;
    }




}


