//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCarreras5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        public int IdParticipante { get; set; }
        public int IdCarrera { get; set; }
        public string chip { get; set; }
        public string apellidos { get; set; }
        public string nombre { get; set; }
        public string dni { get; set; }
        public Nullable<int> posicionGeneral { get; set; }
        public Nullable<System.TimeSpan> tiempoOficial { get; set; }
        public int dorsal { get; set; }
    
        public virtual carrera carreras { get; set; }
        public virtual chip chips { get; set; }
    }
}
